### PR TITLE
Fix download button

### LINKED ISSUE #207: [Bug] Download button same on active and archive
### Expected Behavior

Download button on active page should only download active items, and same for archive page.

### Steps to Reproduce

Click download data on active or archive page and see that they're the same

### Device Information

Desktop/Mobile: Desktop
OS: macOS Monterey 12.3.1
Browser Version: Safari 15.4

### PR DESCRIPTION
**Pull request by michellejli77**
# Description

Previously, the download button would download the same data regardless of what page the user is on. The download button on the active page should only download active items into a csv and same for the archived page.

Closes #207 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: client/src/components/TableWidget.tsx [hunk 1]
```diff
@@ -56,7 +56,11 @@ const TableWidget = (props: {
     <div>
       <div className="table-buttons">
         <div>
-          <DownloadDataButton />
+          {!props.isArchivedItems ? (
```
Comment (hdavidethan) [inline client/src/components/TableWidget.tsx:59]: Can simplify to
```
<DownloadDataButton onlyArchived={props.isArchivedItems} />
```

**Review by hdavidethan — APPROVED** [review]
Other than the part that can more concise, everything looks good!

File: client/src/components/TableWidget.tsx (hunk 1 above)
Comment (michellejli77) [reply client/src/components/TableWidget.tsx:59]: o so true
